### ISSUE TITLE
Offtopic: please add an SSL certificate to your website...

### ISSUE THREAD

**Issue by rodgermoore** [MiscellaneousStuff/anterion#5]
I am sure you guys put a lot of time and effort in this project but some basics still apply. Not having a ssl certificate on your website anterion.ai makes people think you might be bunch of amateurs. Let's encrypt provides free ssl certs for your website. Please use it. Good luck with your project and startup.

**Comment by MiscellaneousStuff** [comment]
Thanks Rodger, we’ll add it to the list for today!
