### ISSUE TITLE
Please provide example .env file

### ISSUE THREAD

**Issue by 1of13** [MiscellaneousStuff/anterion#6]
Let me begin by saying that I appreciate your hard work and dedication to Anterion. 

I want to check it out, but I need help installing it. I'm on a Mac and can't correctly complete the required information in the .env file. For example, my docker volumes are found in "~/Library/Containers/com.docker.docker/Data/vms/", but this seems to be incorrect. 

Would it be possible for you to provide an example? It would greatly assist me in finding the required information and ensure a smoother installation process.

Thank you,

1of13

**Comment by Lucas-Strange** [comment]
We'll be releasing a tutorial shortly:)

**Comment by 1of13** [comment]
Thank you so much for the tutorial. Anterion kicks ass!
